### ISSUE TITLE
Compilation fails after upgrading ngx-leaflet-draw to v18

### ISSUE THREAD

**Issue by pkurcx** [Asymmetrik/angular2-leaflet-draw#150]
```
✘ [ERROR] Angular compilation initialization failed. [plugin angular-compiler]

  Error: Cannot resolve type entity i2.LeafletModule to symbol
      at reflectTypeEntityToDeclaration (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-TPUY2KMQ.js:727:11)
      at extraReferenceFromTypeQuery (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:1481:26)
      at file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:1476:12
      at Array.map (<anonymous>)
      at extractReferencesFromType (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:1472:23)
      at DtsMetadataReader.getNgModuleMetadata (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:1682:16)
      at MetadataDtsModuleScopeResolver.resolve (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:3914:37)
      at LocalModuleScopeRegistry.getExportedScope (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:4236:41)
      at LocalModuleScopeRegistry.getScopeOfModuleReference (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:4095:32)
      at LocalModuleScopeRegistry.getScopeOfModule (file:///Users/user/IdeaProjects/project/angular/node_modules/@angular/compiler-cli/bundles/chunk-CDSIZK6E.js:4043:47)
```

```json
{
  "name": "frontend",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {

  },
  "private": true,
  "engines": {
    "node": "^20.11.0"
  },
  "dependencies": {
    "@angular/animations": "18.0.1",
    "@angular/cdk": "18.0.1",
    "@angular/common": "18.0.1",
    "@angular/compiler": "18.0.1",
    "@angular/core": "18.0.1",
    "@angular/flex-layout": "15.0.0-beta.42",
    "@angular/forms": "18.0.1",
    "@angular/localize": "18.0.1",
    "@angular/material": "18.0.1",
    "@angular/material-moment-adapter": "18.0.1",
    "@angular/platform-browser": "18.0.1",
    "@angular/platform-browser-dynamic": "18.0.1",
    "@angular/router": "18.0.1",
    "@angular/service-worker": "18.0.1",
    "@asymmetrik/ngx-leaflet": "18.0.1",
    "@asymmetrik/ngx-leaflet-draw": "18.0.0",
    "@asymmetrik/ngx-leaflet-markercluster": "18.0.0",
    "leaflet": "1.7.1",
    "leaflet-draw": "1.0.4",
    "leaflet-draw-drag": "0.4.8",
    "leaflet.marker.slideto": "0.2.0",
    "leaflet.markercluster": "1.5.0",
    "rxjs": "7.8.1",
    "tslib": "2.6.2",
    "zone.js": "0.14.6"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "18.0.2",
    "@angular-devkit/core": "18.0.2",
    "@angular-devkit/schematics": "18.0.2",
    "@angular-eslint/builder": "18.0.1",
    "@angular-eslint/eslint-plugin": "18.0.1",
    "@angular-eslint/eslint-plugin-template": "18.0.1",
    "@angular-eslint/template-parser": "18.0.1",
    "@angular/cli": "18.0.2",
    "@angular/compiler-cli": "18.0.1",
    "@angular/elements": "18.0.1",
    "@angular/language-service": "18.0.1",
    "@angular/platform-server": "18.0.1",
    "@nx/angular": "19.1.1",
    "@nx/cypress": "19.1.1",
    "@nx/eslint": "19.1.1",
    "@nx/eslint-plugin": "19.1.1",
    "@nx/jest": "19.1.1",
    "@nx/js": "19.1.1",
    "@nx/linter": "19.1.1",
    "@nx/node": "19.1.1",
    "@nx/workspace": "19.1.1",
    "@schematics/angular": "18.0.2",
    "@types/leaflet": "1.7.0",
    "@types/leaflet-draw": "1.0.11",
    "@types/leaflet.markercluster": "1.4.0",
    "@types/lodash-es": "4.17.12",
    "@types/node": "20.11.0",
    "ng-packagr": "18.0.0",
    "nx": "19.1.1",
    "patch-package": "8.0.0",
    "sass": "1.75.0",
    "ts-node": "10.9.2",
    "typescript": "5.4.5"
  }
}

```

**Comment by reblace** [comment]
Can you try switching to the @bluehalo namespace artifacts for:

"@asymmetrik/ngx-leaflet": "18.0.1",
"@asymmetrik/ngx-leaflet-draw": "18.0.0",
"@asymmetrik/ngx-leaflet-markercluster": "18.0.0",

**Comment by pkurcx** [comment]
I wll try

**Comment by pkurcx** [comment]
Same error

**Comment by reblace** [comment]
ok, I'm working through building a non-standalone project with draw and markercluster and I'm updating documentation as I go. will let you know if I find anything
